before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Eq1J1ddSl3s9tT7IxOIzVKpJHOV6e51wiZmIGYGpKHbrAoji7LTiCDHUxPUS8tsY+dvEffxOlM0eIzqhdQVQEn2piFeR9HXfGwwzk7/t6r0WdJwCMb+ineRW+kwm20pPWk2wWdqyF6G4xlQKNlLEmiBPjTqQA4j65O31mRRGytARKR8SS9TdiCGTpoTExmWoOwrFfH2n/Ytdby71YxlS1khv0lZF/2ZeasC6WS1+F4Mr2gY5GhFz6o25y6w+SWKUuvohK9k4u39xFm0gmBSCEsA8LNW/LCw+2sozQ0mxn13bSPedbgFGxomvARI34cW8QQgxbvfc/7rbZ+gzNKOntN8QfKAg2BoC7gq+EPpNylccu33DtqxPkU21LjC1ASeIh4/CfBUeE0scm8vwGOCe0PGMavf3fvy2CCRd/RtxN19/jxzOP380n8au7H5GuntRspDz5jgwBDm3Z24jaM4H50INFuKN2Zo9GcCjqCCiNkTzPtBSjWQljhTqdlrPZZ2/rdDqtRLogq0o3BXqBOuVG3QAEKcVHCc+ODzU84rzI6K7vRO5OktJ5/gaSaXiFRt+eg0n1R88L5TUQjDKM5SU7M+edZsLnosdl8PrUYRbvhFLCjNS84tN/tFxlTqUHXYz8QVvTihhjHUsdTfPNae5XdNFcb9gbsM6Pxk4u9A/Ml4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
